version: "3"
services:
    redis-server:
        image: "redis"
    node-app:
        restart: on-failure
        build: .
        ports:
           - 5000:5000
        environment:
           - REDIS_HOST=redis-server
           - REDIS_PORT=6379
           - REACT_APP_FRONTED_URL = "http://localhost:3000"
        volumes:
            - /app/node_modules
            - .:/app
        
